import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavBar } from "@/components/NavBar";
import { AnimatedTooltip } from "@/components/ui/AnimatedTooltip";
import Link from "next/link";
import { myInfo } from "./globalConstants";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="fixed w-full left-0 bottom-10 z-50">
          <NavBar />
        </div>
        <Link
          href={"https://github.com/Aayush259"}
          target="_blank"
          className="fixed right-20 bottom-10 z-50">
          <AnimatedTooltip items={[myInfo]} />
        </Link>
      </body>
    </html>
  );
}
